import "./globals.css";
import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const ubuntu = Ubuntu({
	subsets: ["latin"],
	weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
	title: "KanbanAI",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${ubuntu.className} m-0 mx-auto w-screen`}>
				<>
					{children}
					<ToastContainer
						position="top-right"
						autoClose={3000}
						closeOnClick
					></ToastContainer>
				</>
			</body>
		</html>
	);
}
